#!/usr/bin/env python
"""
Convert extended "adjacency dot" format to standard dot format.
Example:

graph G {
    a: [b, c]
}

|
v

graph G {
    a -- b
    a -- c
}
"""

import sys


def convert(inp, outp):
    l = inp.readline()
    outp.write(l)
    edges = set()
    for l in inp:
        ls = l.strip()
        if not ls:
            continue
        if ls == "}":
            outp.write(l)
            break
        if ": [" in l:
            src, dests = [x.strip() for x in l.split(":")]
            if dests[-1] == ",":
                dests = dests[:-1]
            assert dests[0] == "[" and dests[-1] == "]"
            dests = dests[1:-1]
            for d in dests.split(","):
                d = d.strip()
                if src < d:
                    e = (src, d)
                else:
                    e = (d, src)
                if e not in edges:
                    outp.write("%s -- %s\n" % e)
                    edges.add(e)
        else:
            outp.write(l)


if __name__ == "__main__":
    convert(open(sys.argv[1]), open(sys.argv[2], "w"))
